import type {
  IPostRepository,
  PostFilters,
} from "@/repositories/interfaces/IPostRepository";
import type { Post } from "@/models/post";
import SupabaseService from "@/lib/supabase";

export class SupabasePostRepository implements IPostRepository {
  private get client() {
    return SupabaseService.getInstance().getClient();
  }

  private mapToModel(data: any): Post {
    return {
      ...data,
      submolt_id: data.submolt_id || data.submolt, // Fallback if view differs
      text: data.text || data.content,
      author: { name: data.author_name || "Unknown" },
      cont_type: "post",
    };
  }

  async findById(id: string): Promise<Post | null> {
    try {
      const { data, error } = await this.client
        .from("posts")
        .select("*")
        .eq("id", id)
        .single();

      if (error) throw error;
      return this.mapToModel(data);
    } catch (error) {
      console.error("SupabasePostRepository.findById error:", error);
      return null;
    }
  }

  async findBySubmolt(submoltName: string): Promise<Post[]> {
    return this.findAll({ submolt: submoltName });
  }

  async findByAuthor(authorName: string): Promise<Post[]> {
    return this.findAll({ author: authorName });
  }

  async findAll(filters: PostFilters = {}): Promise<Post[]> {
    try {
      let query = this.client.from("posts").select("*");

      if (filters.submolt) {
        query = query.eq("submolt", filters.submolt);
      }

      if (filters.author) {
        query = query.eq("author_name", filters.author);
      }

      if (filters.sort === "new") {
        query = query.order("created_at", { ascending: false });
      } else if (filters.sort === "top") {
        query = query.order("upvotes", { ascending: false });
      } else if (filters.sort === "rising") {
        query = query.order("created_at", { ascending: false });
      } else {
        query = query.order("created_at", { ascending: false });
      }

      if (filters.limit) {
        query = query.limit(filters.limit);
      }

      const { data, error } = await query;

      if (error) throw error;
      return (data || []).map(this.mapToModel);
    } catch (error) {
      console.error("SupabasePostRepository.findAll error:", error);
      return [];
    }
  }

  async create(
    data: Omit<
      Post,
      "id" | "upvotes" | "downvotes" | "created_at" | "is_pinned" | "author" | "type"
    >,
  ): Promise<Post> {
    const dbPost = {
      // id: generated by db or if we want to enforce it here
      // For now let Supabase handle ID generation or use a UUID
      // But if we need to return it immediately with the ID we generated:
      // id: `post_${Date.now()}`, // Removed purely for DB generation preference, but user code implies consistent ID format.
      // Let's rely on DB generation but if the model requires it returned... 
      // Supabase returns the generated ID.
      title: data.title,
      text: data.text,
      // url: data.url, // Removed as not in Post model
      submolt_id: data.submolt_id,
      author_id: data.author_id,
      is_pinned: false,
      cont_type: "post",
    };

    try {
      const { data: inserted, error } = await this.client
        .from("posts")
        .insert(dbPost)
        .select("*, author:agents(name)")
        .single();

      if (error) throw error;

      // Increment posts_count for the submolt
      // This logic might be better in a database trigger, but keeping it here for parity
      const { data: submolt } = await this.client
        .from("submolts")
        .select("posts_count")
        .eq("id", data.submolt_id) // Assuming using ID now
        .single();

      if (submolt) {
        await this.client
          .from("submolts")
          .update({ posts_count: (submolt.posts_count || 0) + 1 })
          .eq("id", data.submolt_id);
      }

      return this.mapToModel(inserted);
    } catch (error) {
      console.error("SupabasePostRepository.create error:", error);
      throw error;
    }
  }

  async delete(id: string): Promise<boolean> {
    try {
      const { error } = await this.client.from("posts").delete().eq("id", id);
      return !error;
    } catch (error) {
      console.error("SupabasePostRepository.delete error:", error);
      return false;
    }
  }

  async incrementUpvotes(id: string): Promise<Post | null> {
    try {
      const { data: post, error: fetchError } = await this.client
        .from("posts")
        .select("upvotes")
        .eq("id", id)
        .single();

      if (fetchError || !post) return null;

      const { data: updated, error } = await this.client
        .from("posts")
        .update({ upvotes: post.upvotes + 1 })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return this.mapToModel(updated);
    } catch (error) {
      console.error("SupabasePostRepository.incrementUpvotes error:", error);
      return null;
    }
  }

  async incrementDownvotes(id: string): Promise<Post | null> {
    try {
      const { data: post, error: fetchError } = await this.client
        .from("posts")
        .select("downvotes")
        .eq("id", id)
        .single();

      if (fetchError || !post) return null;

      const { data: updated, error } = await this.client
        .from("posts")
        .update({ downvotes: post.downvotes + 1 })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return this.mapToModel(updated);
    } catch (error) {
      console.error("SupabasePostRepository.incrementDownvotes error:", error);
      return null;
    }
  }

  async togglePin(id: string, pinned: boolean): Promise<Post | null> {
    try {
      const { data: updated, error } = await this.client
        .from("posts")
        .update({ is_pinned: pinned })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return this.mapToModel(updated);
    } catch (error) {
      console.error("SupabasePostRepository.togglePin error:", error);
      return null;
    }
  }
}
